### ISSUE TITLE
unirest uses old version of rest-client

### ISSUE THREAD

**Issue by sina-s** [filestack/filestack-ruby#17]
I'm not able to use this gem due to conflicting `rest-client` gem version with some other gems I have in my project. One of the gems require `rest-client >= 2.0` and filestack-ruby requires unirest which requires the older `rest-client (~> 1.6.7)`. I would have opened an issue upon unirest but it seems like it's unmaintained and there are a bunch of other old dependency issues in there: look at https://github.com/Kong/unirest-ruby/issues/45 and 
https://github.com/Kong/unirest-ruby/issues/33

**Comment by pmichaeljones** [comment]
Any suggestions guys? **rest-client 1.6.7** has a known vulnerability, but since Filestack has a dependency on **unirest 1.1.2** it's impossible to update rest-client without removing Filestack-Ruby.

**Comment by gabifiolek** [comment]
We will fix the issue in new version of Ruby SDK

**Comment by thejspr** [comment]
Awesome @gabifiolek! Any idea when this new version will be released?

**Comment by pmichaeljones** [comment]
Hey @gabifiolek Any idea on an update?

**Comment by gabifiolek** [comment]
@sina-s we actually updated the library to version 2.3.0 with some changes.
