### ISSUE TITLE
How to save metadata to @user.filestack_url

### ISSUE THREAD

**Issue by masudhossain** [filestack/filestack-ruby#20]
I'm currently doing 
`<%= f.filestack_field :filepicker_url, 'Upload Your Avatar!', id: 'unique-id' %> 
`to upload files and it's working fine. but I also want to save the metadata (such as name, filetype, ect.) to my rails application. Otherwise, i can't grab the name of the files for my users to see.

**Comment by staturecrane** [comment]
Please see: https://github.com/filestack/filestack-rails/issues/176

**Comment by masudhossain** [comment]
Okay so how would you go about doing it with this ruby gem?
