### ISSUE TITLE
Filestack scanning viruses

### ISSUE THREAD

**Issue by huyvohcmc** [filestack/filestack-ruby#33]
Sorry to ask this question but does filestack scan viruses for every uploaded file? Is there a doc somewhere?

**Comment by julioalucero** [comment]
Why was close?

**Comment by huyvohcmc** [comment]
@julioalucero because it doesn't.

**Comment by julioalucero** [comment]
@huyvohcmc Filestack support it https://www.filestack.com/docs/concepts/workflows/virus-detection/.
But seems that this library still does not support send something like:
```js
client.upload(filepath: 'tmp/test.pdf', options: {'workflows': ["23dfd7cb-359e-4e53-8918-dca35790a74b"]})
```

**Comment by julioalucero** [comment]
For the records, the correct url is: 
`https://cdn.filestackcontent.com/<APIKEY>/store=workflows:["<workflow_id>"]/<external-url>`

**Comment by julioalucero** [comment]
Updated:
To use a Workflow the correct url is to use the workflow_id without quotes:

`https://cdn.filestackcontent.com/<APIKEY>/store=workflows:[<workflow_id>]/<external-url>`

Example:
"https://cdn.filestackcontent.com/DFDmms4UET7iE234ma32G2343/store=workflows:[jskfj9023-359e-4e53-8918-ajsdklfj90238493]/https://cdn.filestackcontent.com/kdjfkj90234293kjsdf"

**Comment by gaaabiko** [comment]
@julioalucero @huyvohcmc I apologize for a late reponse. In filestack-ruby 2.7.0, I've added a workflows support.
Now you should be able to do: `client.upload(filepath: 'tmp/test.pdf', options: { workflows: ["23dfd7cb-359e-4e53-8918-dca35790a74b"]})`.
Let me know if it helps.
