### ISSUE TITLE
Support setting mimetype in uploads

### ISSUE THREAD

**Issue by cmunozgar** [filestack/filestack-ruby#39]
I couldn't find the way to set the `mimetype` option on the upload of an external_url as you can use through the API: [https://www.filestack.com/docs/api/file/#store](https://www.filestack.com/docs/api/file/#store).

So I ended up doing this on: 
`client = FilestackClient.new("#{ENV['FILESTACK_API_KEY']}&imagetype=image/jpeg")` 
because I saw it in [https://github.com/filestack/filestack-ruby/blob/master/lib/filestack/utils/utils.rb#L86](https://github.com/filestack/filestack-ruby/blob/master/lib/filestack/utils/utils.rb#L86).

Is there a cleaner way to do this?

**Comment by gabifiolek** [comment]
@cmunozgar if you want to upload file and set the mimetype, you have to pass query params (https://www.filestack.com/docs/api/file/#store-qp) in options.

Here is an example:
`require 'filestack'

client = FilestackClient.new('YOUR_APIKEY')
filelink = client.upload(filepath: 'filename.css', options: {'mimetype': 'text/css'})
puts filelink.url`

Let me know if that helps :)

**Comment by gabifiolek** [comment]
@cmunozgar We have added some changes to version `2.5.3`, so if you want to upload `external_url` you have to pass query params in options (same as I wrote above):
Example:
`require 'filestack'`

`client = FilestackClient.new('YOUR_APIKEY')`
`ilelink = client.upload(external_url: 'https://someimage.png', options: {'mimetype': 'image/jpeg'})`
`puts filelink.url`
