### ISSUE TITLE
Missing 'cache' Transformation

### ISSUE THREAD

**Issue by rtymchyk** [filestack/filestack-ruby#52]
I notice that `cache` is not a valid item under `TRANSFORMATIONS`. For example, I'd like to be able to do:

`transform.cache(expiry: 'max')`

Is there any reason why I cannot create a PR to whitelist it?

**Comment by rtymchyk** [comment]
Pull request ready ^

**Comment by gabifiolek** [comment]
Already fixed! 👍

**Comment by rtymchyk** [comment]
Ty
