### ISSUE TITLE
Gemspec is out of date and too restrictive

### ISSUE THREAD

**Issue by kiskoza** [filestack/filestack-ruby#60]
I'm trying to do a maintenance job on a project that uses `filestack-ruby`. To be able to use latest 5.x Rails, I need to upgrade some of the gems. One of them requires `parallel` with minimum version of `0.12`, which is not compatible with `filestack-ruby`'s requirements.

**Comment by gabifiolek** [comment]
@kiskoza Thank you for letting us know!
I've just updated the version of the parallel gem in `filestack-ruby 2.6.5`
