### ISSUE TITLE
Reading data from IO object

### ISSUE THREAD

**Issue by zeitnot** [filestack/filestack-ruby#64]
As far as I know this gem does not support reading data from IO object. It only accepts file path. Most of the time we produce the content on the memory so we do not have physical file. Filestack gem forces us to save this data on the disk then giving the file path. This hurts the performance due to many system calls. It would be very nice if it supports to accept an IO object like the following. 

```ruby
  file = StringIO.new
  client = FilestackClient.new(ENV['KEY'])
  file_link = client.upload(io: file)
```

**Comment by zeitnot** [comment]
Is there any progress for this issue?

**Comment by gabifiolek** [comment]
@zeitnot Thanks your the message. I'll add soon.

**Comment by gabifiolek** [comment]
@zeitnot Thank you for the comment. I'll add it soon.

**Comment by gaaabiko** [comment]
@zeitnot I've added IO object upload to filestack 2.8.0. I hope it helps. But please let me know if you face any issues. Happy to help.

**Comment by zeitnot** [comment]
@gaaabiko Many thanks.
