### ISSUE TITLE
docs provider error: conversion was taking too long (idx 0)

### ISSUE THREAD

**Issue by gdomingu** [filestack/filestack-ruby#66]
Hi there, when I try to do a 
```
client.upload(external_url: url)
```
I sometimes get an error

```
*** JSON::ParserError Exception: 435: unexpected token at 'uuid=API-XXXXXX] Invalid response when trying to read from http://internal-taskrouters-...
```

When visiting the API url in my browser the response is

```
docs provider error: conversion was taking too long (idx 0)
```

Is there a way to increase the timeout for this? Or when this error happens have the API response with some JSON so that the gem doesn't get upset?

**Comment by gabifiolek** [comment]
@gdomingu Hi! Thank you for letting us know. I will take a look on that asap.

**Comment by gabifiolek** [comment]
@gdomingu In Filestack, we setup a default limit for docs conversion, but we can change it for our customers. If you are interested in increasing timeout, please contact our sales.
I'm going to close the ticket, but please reopen if you have any doubts.
