### ISSUE TITLE
Json Parse Error

### ISSUE THREAD

**Issue by gdomingu** [filestack/filestack-ruby#70]
Hi there!

We use this gem to upload to filestack but we get a bunch of `JSON::ParserError` anytime something goes wrong with the upload on filestack. Ideally the filestack server would be better about returning JSON even when something goes wrong, but I thought this gem could handle when the response is not in JSON as well. 

Here is a PR with a proposed solution https://github.com/filestack/filestack-ruby/pull/69

**Comment by gaaabiko** [comment]
@gdomingu thank you for the comments and PR. I will update it as soon as possible.

**Comment by gaaabiko** [comment]
Changed was released in filestack-ruby 2.8.1.
