### ISSUE TITLE
bootsnap, rails test

### ISSUE THREAD

**Issue by PeterAMooney** [filestack/filestack-ruby#74]
When I run rails rest command I get the following error message.

/home/ubuntu/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:34:in `require': cannot load such file -- rexml/document (LoadError)

this is the gem i have installed.

**Comment by gaaabiko** [comment]
@PeterAMooney I assume that you have Rails application where Ruby version is 3.0.0. I've setup test app, and I've run `rails test`.
Adding `rexml` in the test group in the Gemfile fixes the issue.
`group :test do`
  `gem 'webdrivers'`
  `gem 'rexml'`
end`

Let me know if that help.
