### ISSUE TITLE
Yanked mimemagic versions and GPL2

### ISSUE THREAD

**Issue by PhilCoggins** [filestack/filestack-ruby#77]
Early this morning, mimemagic (a dependency in your project) resolved a licensing issue by updating their license from MIT to GPL 2 and yanking all old versions. The maintainer has made 0.3.6 available which resolves the `mimemagic (~> 0.3.2)` dependency, but it is now licensed as GPL 2, which (IANAL) makes all derived works (including your library, and users of your library) GPL 2.

See https://github.com/minad/mimemagic/issues/97, https://github.com/minad/mimemagic/issues/98, and https://github.com/rails/rails/issues/41750.

[There is a MIT-compatible fork](https://github.com/jellybob/mimemagic/issues/1) in the works. My question is, does Filestack plan to update their libraries to not be a derived work of GPL 2?

Related: https://github.com/filestack/filestack-ruby/pull/76

**Comment by PhilCoggins** [comment]
Update: Mimemagic now has a new maintainer who has reimplemented the library to be MIT-compatible, all GPL licensed-versions have been yanked. The library requires the external dependency `shared-mime-info` which requires installation on MacOS and smaller linux distros, it may be helpful to update your Readme with this information (happy to help with that, just let me know!)

**Comment by thushw** [comment]
What is the advise for filestack users?

**Comment by gabifija** [comment]
I'm going to update the version to 0.3.8.

**Comment by gabifija** [comment]
@PhilCoggins @thushw - Please check already released filestack 2.9.0.
Let me know if it works as expected.

**Comment by marshals** [comment]
@gabifija Thanks. Looks like you may want to update it to 0.3.9 for https://github.com/mimemagicrb/mimemagic/issues/106

**Comment by gabifija** [comment]
> @gabifija Thanks. Looks like you may want to update it to 0.3.9 for [mimemagicrb/mimemagic#106](https://github.com/mimemagicrb/mimemagic/issues/106)

Thank you! Updated. 
Let me know if you notice any issues. I'll fix that.
